import Head from 'next/head'

import Nav from '../components/nav'
import Hero from '../components/hero'
import Work from '../components/work'
import Extension from '../components/extension'
import Customize from '../components/customize'
import Pricing from '../components/pricing'
import Task from '../components/task'
import Data from '../components/data'
import Sponsors from '../components/sponsors'
import Apps from '../components/apps'
import Testomonial from '../components/testomonial'
import Trial from '../components/trial'
import Footer from '../components/footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Whitespace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet"></link>
      </Head>

      <main className='font-inter'>
        <Nav />
        <Hero />
        <Work />
        <Extension />
        <Customize />
        <Pricing />
        <Task />
        <Data />
        <Sponsors />
        <Apps />
        <Testomonial />
        <Trial />
        <Footer />
      </main>
    </div>
  )
}
